Models/Duty.cs
namespace ToDo.WebApp.Models;

public class Duty:Entity
{
	public string Name { get; set; }
	public string dutyDate { get; set; }
	public string priorityLevel { get; set; }
	public string Category { get; set; }
	}

Models/Entity.cs
namespace ToDo.WebApp.Models;

public class Entity
{
	public int Id { get; set; }
	
}

Models/ErrorViewModel.cs
namespace ToDo.WebApp.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Models/Show.cs
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ToDo.WebApp.Models;

public class Show:Entity
{
	[NotMapped]
	public string Category { get; set; }
	[NotMapped]
	public string Status { get; set; }
    public  int UserId { get; set; }
	public int DutyId { get; set; }

    [NotMapped]
    public string? UserName { get; set; }

    [NotMapped]
    public string? DutyName { get; set; }

	[NotMapped]
	public string DutyDate { get; set; }
    
    [NotMapped]
	public string UserDate { get; set; }

	[NotMapped]
	public string Priority { get; set; }

	[NotMapped]
	public List<SelectListItem> DutyList { get; set;}

	[NotMapped]
	public List<SelectListItem> UserList { get; set;}
}

Models/User.cs
namespace ToDo.WebApp.Models;

public class User: Entity
{
	public string Name { get; set; }
	public string Email { get; set; }
	public string Password { get; set; }
	public string DateOnly { get; set; }

}

Controllers/DutyController.cs
using Microsoft.AspNetCore.Mvc;
using ToDo.WebApp.Models;
using ToDo.WebApp.Repository.Abstract;

namespace ToDo.WebApp.Controllers;

public class DutyController : Controller
{
	private readonly IDutyRepository _dutyRepository;
	public DutyController(IDutyRepository dutyRepository)
	{
        _dutyRepository = dutyRepository;
	}
	public IActionResult Index()
	{
		var dutys = _dutyRepository.GetAll();
		return View(dutys);
	}
	[HttpGet]
	public IActionResult Create()
	{
		return View();
	}
	[HttpPost]
	public IActionResult Create(Duty duty)
	{
        _dutyRepository.Add(duty);
		return RedirectToAction("Create");
	}
	[HttpGet]
	public IActionResult Delete(int id)
	{
        _dutyRepository.Delete(id);
		return RedirectToAction("Index");
	}
	[HttpGet]
	public IActionResult Update(int id)
	{
		var modelId = _dutyRepository.GetById(id);
		return View(modelId);
	}
	[HttpPost]
	public IActionResult Update(Duty duty)
	{
        _dutyRepository.Update(duty);
		return RedirectToAction("Index");
	}


}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ToDo.WebApp.Models;

namespace ToDo.WebApp.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Controllers/ShowController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ToDo.WebApp.Models;
using ToDo.WebApp.Repository.Abstract;

namespace ToDo.WebApp.Controllers;

public class ShowController : Controller
{
	private readonly IShowRepository _showRepository;
	private readonly IUserRepository _userRepository;
	private readonly IDutyRepository _dutyRepository;

	public ShowController(IShowRepository showRepository, IUserRepository userRepository, IDutyRepository dutyRepository)
	{
		_showRepository = showRepository;
		_userRepository = userRepository;
        _dutyRepository = dutyRepository;
	}
	public IActionResult Index()
	{
		var lists = _showRepository.GetAll();
		return View(lists);
	}
	[HttpGet]
	public IActionResult Create()
	{
		var model = new Show();
		model.UserList = _userRepository.GetAll().Select(a => new SelectListItem{ Text = a.Name,Value = a.Id.ToString()}).ToList();
		model.DutyList =_dutyRepository.GetAll().Select(a => new SelectListItem { Text = a.Name, Value = a.Id.ToString()}).ToList();
		return View(model);
	}
	[HttpPost]
	public IActionResult Create(Show show)
	{
		show.UserList = _userRepository.GetAll().Select(a=> new SelectListItem { Text = a.Name,Value=a.Id.ToString(),Selected = a.Id == show.UserId}).ToList();
		show.DutyList = _dutyRepository.GetAll().Select(a => new SelectListItem { Text = a.Name, Value = a.Id.ToString(), Selected = a.Id == show.DutyId }).ToList();
		_showRepository.Add(show);
		return RedirectToAction("Create");
	}
	[HttpGet]
	public IActionResult Delete(int id)
	{
		_showRepository.Delete(id);
		return RedirectToAction("Index");
	}
	[HttpGet]
	public IActionResult Update(int id)
	{
		var modelId = _showRepository.GetById(id);
		modelId.UserList = _userRepository.GetAll().Select(a => new SelectListItem { Text = a.Name, Value = a.Id.ToString(), Selected = a.Id == modelId.UserId }).ToList();
		modelId.DutyList = _dutyRepository.GetAll().Select(a => new SelectListItem { Text = a.Name, Value = a.Id.ToString(),Selected = a.Id==modelId.DutyId}).ToList();
		return View(modelId);
	}
	[HttpPost]
	public IActionResult Update(Show show)
	{
		show.UserList = _userRepository.GetAll().Select(a => new SelectListItem{ Text = a.Name, Value = a.Id.ToString(),Selected = a.Id == show.UserId}).ToList();
		show.DutyList = _dutyRepository.GetAll().Select(a => new SelectListItem { Text = a.Name, Value = a.Id.ToString(),Selected = a.Id == show.DutyId}).ToList();
		_showRepository.Update(show);
		return RedirectToAction("Index");
	}


}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using ToDo.WebApp.Models;
using ToDo.WebApp.Repository.Abstract;
using ToDo.WebApp.Repository.Implementation;

namespace ToDo.WebApp.Controllers;

public class UserController : Controller
{
	private readonly IUserRepository _userRepository;
    public UserController(IUserRepository userRepository)
    {
        _userRepository = userRepository;
    }
    public IActionResult Index()
	{
		var users = _userRepository.GetAll();
		return View(users);
	}
	[HttpGet]
	public IActionResult Create()
	{
		return View();
	}
	[HttpPost]
	public IActionResult Create(User user)
	{
		_userRepository.Add(user);
		return RedirectToAction("Create");
	}
	[HttpGet]
	public IActionResult Delete(int id)
	{
		_userRepository.Delete(id);
		return RedirectToAction("Index");
	}
	[HttpGet]
	public IActionResult Update(int id)
	{
		var modelId = _userRepository.GetById(id);
		return View(modelId);
	}
	[HttpPost]
	public IActionResult Update(User user)
	{
		_userRepository.Update(user);
		return RedirectToAction("Index");
	}


}

Views/Duty/Create.cshtml
@model Duty

<div class="container pt-5">
	<div class="row">
		<div class="col-md-6">
			<form asp-controller="Duty" asp-action="Create" method="post">
				<div class="form-group">
					<label asp-for="Name" class="form-label">Görev İsmi *</label>
					<input asp-for="Name" type="text" class="form-control">
					<span asp-validation-for="Name" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="Category" class="form-label">Kategori </label>
					<input asp-for="Category" type="text" class="form-control">
					<span asp-validation-for="Category" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="dutyDate" class="form-label">Task Başlangıç Tarihi * </label>
					<input asp-for="dutyDate" type="date" class="form-control">
					<span asp-validation-for="dutyDate" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="priorityLevel">Öncelik Durumu</label><br />
					<input type="range" asp-for="priorityLevel" list="markers" />

					<datalist id="markers">
						<option value="0"></option>
						<option value="25"></option>
						<option value="50"></option>
						<option value="75"></option>
						<option value="100"></option>
					</datalist>
				</div>

				

				<div class="form-group pt-3">
					<button type="submit" class="btn btn-warning"><i class="bi bi-save"></i>Kaydet</button>
					<a href="/Duty/Index" class="btn btn-primary"><i class="bi bi-list"></i>Listele</a>
				</div>
			</form>
		</div>
	</div>
</div>

Views/Duty/Index.cshtml
@model IEnumerable<Duty>

<div class="container pt-3">
	<div class="row">
		<div class="col-md-12">
			<h3>Kullanıcılar</h3>
			<table class="table table-striped table-bordered table-dark">
				<thead>
					<tr>
						<th>Görev İsmi</th>
						<th>Görev Başlangıç Tarihi</th>
						<th>Kategori</th>
						<th>Öncelik Durumu</th>
						<th>-</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var item in Model)
					{
						<tr>
							<td>@item.Name</td>
							<td>@item.dutyDate</td>
							<td>@item.Category</td>
							<td>@item.priorityLevel</td>
							<td>
								<a class="btn btn-success" href="/Duty/Update?id=@item.Id"><i class="bi bi-pen"></i></a>
								<a class="btn btn-danger"
								   onclick="return window.confirm('Are you sure?')"
								   href="/Duty/Delete?id=@item.Id"><i class="bi bi-trash"></i></a>
							</td>
						</tr>
					}
				</tbody>
			</table>
			<div class="row">
				<div class="col-md-12">
					<a class="btn btn-dark" href="/Duty/Create">Ekle +</a>
				</div>
			</div>
		</div>
	</div>
</div>

Views/Duty/Update.cshtml
@model Duty
<div class="container pt-5">
	<div class="row">
		<div class="col-md-6">
			<h3>Görev Güncelle</h3>
			<form asp-action="Update" method="post">
				<input type="hidden" asp-for="Id" />
				<div class="form-group">
					<label asp-for="Name" class="form-label">Görev *</label>
					<input asp-for="Name" type="text" class="form-control">
					<span asp-validation-for="Name" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="priorityLevel">Öncelik Durumu</label><br />
					<input type="range" asp-for="priorityLevel" list="markers" />

					<datalist id="markers">
						<option value="0"></option>
						<option value="25"></option>
						<option value="50"></option>
						<option value="75"></option>
						<option value="100"></option>
					</datalist>
				</div>
				<div class="form-group">
					<label asp-for="Category">Kategori </label>
					<input asp-for="Category" type="text" class="form-control" />
				</div>
				

				<div class="form-group pt-3">
					<button type="submit" class="btn btn-warning"><i class="bi bi-save"></i>Kaydet</button>
					<a href="/Duty/Index" class="btn btn-primary"><i class="bi bi-list"></i>Listele</a>
				</div>
			</form>

		</div>
	</div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>ToDo.WebApp</title>
	<link rel="icon" type="image/x-icon" href="~/favicon.ico" />

	<!-- Bootstrap Icons-->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
	<!-- Google fonts-->
	<link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
	<link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
	<!-- SimpleLightbox plugin CSS-->
	<link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
	<!-- Core theme CSS (includes Bootstrap)-->
	<link href="~/css/site.css" rel="stylesheet" />
</head>
<body id="page-top">
	<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
		<div class="container px-4 px-lg-5">
			<a class="navbar-brand" href="/">TO-DO</a>
			<button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
			<div class="collapse navbar-collapse" id="navbarResponsive">
				<ul class="navbar-nav ms-auto my-2 my-lg-0">
					<li class="nav-item">
						<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Create">Kullanıcı</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-dark" asp-area="" asp-controller="Duty" asp-action="Create">Görevler</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-dark" asp-area="" asp-controller="Show" asp-action="Create">To-Do Listesi</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<header class="masthead">
		<div class="container px-4 px-lg-5 h-100">
			<div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">

				<div class="container">
					<main role="main" class="pb-3">@RenderBody()</main>
				</div>

			</div>
		</div>
	</header>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
	<!-- SimpleLightbox plugin JS-->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
	<!-- Core theme JS-->
	<script src="js/scripts.js"></script>
	<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
	<!-- * *                               SB Forms JS                               * *-->
	<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
	<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
	<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>
</html>

Views/Show/Create.cshtml
@model Show

<div class = "container pt-5">
	<div class = "row">
		<div class = "col-md-6">
			<h2>To-Do Oluştur</h2>
			<form asp-action ="Add" method="post">
				<div class="form-group">
					<label asp-for="UserName">Kullanıcı *</label>
					<select asp-for="UserName" asp-items="Model.UserList" class="form-control">
						<option value="">--select--</option>
					</select>
					<span asp-validation-for="UserName" class="text-danger"></span>
				</div>

				<div class="form-group">
					<label asp-for="DutyName">Görev İsmi *</label>
					<select asp-for="DutyName" asp-items="Model.DutyList" class="form-control">
						<option value="">--select--</option>
					</select>
					<span asp-validation-for="DutyName" class="text-danger"></span>
				</div>

				@* <div class="form-group">
					<label asp-for="Category">Kategori Adı *</label>
					<input type="text" class="form-control" asp-for="Category" />
					<span asp-validation-for="Category" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="DutyDate">Görev Tarihi</label>
					<input asp-for="DutyDate" type="date" class="form-control">
				</div>
				<div class="form-group">
					<label asp-for="UserDate">Kullanıcı Giriş Tarihi*</label>
					<input asp-for="UserDate" type="date" class="form-control">
				</div>



				<div class="form-group">
					<label asp-for="Priority">Öncelik Durumu</label><br />
					<input type="range" asp-for="Priority" list="markers" />

					<datalist id="markers">
						<option value="0"></option>
						<option value="25"></option>
						<option value="50"></option>
						<option value="75"></option>
						<option value="100"></option>
					</datalist>
				</div> *@

				<div class="form-group pt-3">
					<button type="submit" class="btn btn-warning"><i class="bi bi-save"></i>Kaydet</button>
					<a href="/Show/Index" class="btn btn-primary"><i class="bi bi-list"></i>Listele</a>
				</div>
			</form>
		</div>
	</div>
</div>

Views/Show/Index.cshtml
@model IEnumerable<Show>
<div class="container pt-4">
	<div class="row">
		<div class="col-md-17">
			<h2>To-Do</h2>
			<table class="table">
				<thead>
					<tr>
						<th scope="col">Kullanıcı</th>
						<th scope="col">Görev İsmi</th>
						<th scope="col">Kategori Adı</th>
						<th scope="col">Görev Başlangıç</th>
						<th scope="col">Kullanıcı Giriş</th>
						<th scope="col">Durum</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var item in Model)
					{
						<tr>
							<td>@item.UserName</td>
							<td>@item.DutyName</td>
							<td>@item.Category</td>
							<td>@item.DutyDate</td>
							<td>@item.UserDate</td>
							<td>@item.Status</td>
							<td>@item.Priority</td>

							<td>
								<a class="btn btn-success" href="/Show/Update?id=@item.Id"><i class="bi bi-pen"></i></a>
								<a class="btn btn-danger"
								   onclick="return window.confirm('Are you sure?')"
								   href="/Show/Delete?id=@item.Id"><i class="bi bi-trash"></i></a>
							</td>
						</tr>
					}
				</tbody>
			</table>
			<div class="row">
				<div class="col-md-12">
					<a class="btn btn-dark" href="/Show/Add">Ekle +</a>
				</div>
			</div>
		</div>
	</div>

Views/Show/Update.cshtml
@model Show

<div class="container pt-5">
    <div class="row">
        <div class="col-md-6">
            <h3>To-Do List Güncelle</h3>
            <form asp-action="Update" method="post">
                <input type="hidden" class="form-control" asp-for="Id" />

                <div class="form-group">
                    <label asp-for="UserName">Kullanıcı *</label>
                    <select asp-for="UserName" asp-items="Model.UserList" class="form-control">
                        <option value="">--select--</option>
                    </select>
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="DutyName">Görev İsmi *</label>
                    <select asp-for="DutyName" asp-items="Model.DutyList" class="form-control">
                        <option value="">--select--</option>
                    </select>
                    <span asp-validation-for="DutyName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Category">Kategori Adı *</label>
                    <input type="text" class="form-control" asp-for="Category" />
                    <span asp-validation-for="Category" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class='col-sm-6'>
                            <div class="form-group">
                                <div class='input-group date' id='datetimepicker5'>
                                    <input asp-for="DutyDate" type='text' class="form-control" data-date-format="YYYY/MM/DD" />
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <script asp-for="DutyDate" type=" text /javascript">
                            $(function () {
                                $('#datetimepicker5').datetimepicker({
                                    pickTime: false
                                });
                            });
                        </script>
                    </div>
                </div>


                <div class="form-group">
                    <div class="row">
                        <div class='col-sm-6'>
                            <div class="form-group">
                                <div class='input-group date' id='datetimepicker5'>
                                    <input asp-for="UserDate" type='text' class="form-control" data-date-format="YYYY/MM/DD" />
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <script asp-for="UserDate" type=" text /javascript">
                            $(function () {
                                $('#datetimepicker5').datetimepicker({
                                    pickTime: false
                                });
                            });
                        </script>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="Priority">Öncelik Durumu</label><br />
                    <input type="range" asp-for="Priority" list="markers" />

                    <datalist id="markers">
                        <option value="0"></option>
                        <option value="25"></option>
                        <option value="50"></option>
                        <option value="75"></option>
                        <option value="100"></option>
                    </datalist>
                </div>
                
                <div class="form-group pt-3">
                    <button type="submit" class="btn btn-warning"><i class="bi bi-save"></i>Kaydet</button>
                    <a href="/Show/Index" class="btn btn-primary"><i class="bi bi-list"></i>Listele</a>
                </div>
            </form>

        </div>
    </div>
</div>

Views/User/Create.cshtml
@model User
<div class="container pt-5">
	<div class="row">
		<div class="col-md-6">
			<form asp-controller="User" asp-action="Create" method="post" >

				<div class="mb-3">
					<label asp-for="Name" class="form-label">Kullanıcı İsim Soyisim *</label>
					<input asp-for="Name" type="text" class="form-control">
					<span asp-validation-for="Name" class="text-danger"></span>
				</div>

				<div class="form-group">
					<label asp-for="Email">Email adresi *</label>
					<input type="email" asp-for="Email" class="form-control">
					<small id="emailHelp" class="form-text text-muted">Email'ini kimseyle paylaşmayacağız.</small>
				</div>

				<div class="form-group">
					<label asp-for="Password">Şifre</label>
					<input asp-for="Password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
				</div>
				<div class="form-group">
					<label asp-for="DateOnly">Kullanıcı Katılım Tarihi*</label>
					<input asp-for="DateOnly" type="date" class="form-control">
				</div>

				<div class="form-group pt-3">
					<button type="submit" class="btn btn-warning"><i class="bi bi-save"></i>Kaydet</button>
					<a href="/User/Index" class="btn btn-primary"><i class="bi bi-list"></i>Listele</a>
				</div>
			</form>
		</div>
	</div>
</div>

Views/User/Index.cshtml
@model IEnumerable<User>

<div class="container pt-3">
	<div class="row">
		<div class ="col-md-12">
			<h3>Kullanıcılar</h3>
			<table class="table table-striped table-bordered table-dark">
				<thead>
					<tr>
						<th>Kullanıcı İsmi</th>
						<th>Email</th>
						<th>Katılım Tarihi</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					@foreach(var item in Model)
					{
						<tr>
							<td>@item.Name</td>
							<td>@item.Email</td>
							<td>@item.DateOnly</td>
							<td>
								<a class="btn btn-success" href="/User/Update?id=@item.Id"><i class="bi bi-pen"></i></a>
								<a class="btn btn-danger" 
								onclick="return window.confirm('Are you sure?')"
								   href="/User/Delete?id=@item.Id"><i class="bi bi-trash"></i></a>
							</td>
						</tr>
					}
				</tbody>
			</table>
			<div class="row">
				<div class="col-md-12">
					<a class="btn btn-dark" href="/User/Create">Ekle +</a>
				</div>
			</div>
		</div>
	</div>
</div>

Views/User/Update.cshtml
@model User
<div class="container pt-5">
	<div class="row">
		<div class="col-md-6">
			<h3>Kullanıcı Güncelle</h3>
			<form asp-action="Update" method="post">
				<input type ="hidden" asp-for="Id"/>
				<div class="mb-3">
					<label asp-for="Name" class="form-label">Kullanıcı İsim Soyisim *</label>
					<input asp-for="Name" type="text" class="form-control">
					<span asp-validation-for="Name" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="Email">Email adresi *</label>
					<input type="email" asp-for="Email" class="form-control">
					<small id="emailHelp" class="form-text text-muted">Email'ini kimseyle paylaşmayacağız.</small>
				</div>
				<div class="form-group">
					<label asp-for="Password">Şifre</label>
					<input asp-for="Password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
				</div>
				<div class="form-group">
					<div class="row">
						<div class='col-sm-6'>
							<div class="form-group">
								<div class='input-group date' id='datetimepicker5'>
									<input asp-for="DateOnly" type='text' class="form-control" data-date-format="YYYY/MM/DD" />
									<span class="input-group-addon">
										<span class="glyphicon glyphicon-calendar"></span>
									</span>
								</div>
							</div>
						</div>
						<script asp-for="DateOnly" type=" text /javascript">
							$(function () {
								$('#datetimepicker5').datetimepicker({
									pickTime: false
								});
							});
						</script>
					</div>
				</div>
				
				<div class="form-group pt-3">
					<button type="submit" class="btn btn-warning"><i class="bi bi-save"></i>Kaydet</button>
					<a href="/User/Index" class="btn btn-primary"><i class="bi bi-list"></i>Listele</a>
				</div>
			</form>

		</div>
	</div>
</div>